source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'mysql2'
gem 'sprockets'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'execjs'
gem 'bootstrap-wysihtml5-rails'
gem 'capistrano'
gem 'whenever'
gem 'therubyracer',  platforms: :ruby
gem 'twitter-bootstrap-rails'
gem 'carrierwave'
gem 'bootstrap_form'
gem 'i18n_country_select'
gem 'rack-cache'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'minecraft-query'
gem 'devise'
gem 'commontator', '~> 4.7.2'
gem 'will_paginate-bootstrap'
gem 'acts_as_votable'
gem 'font-awesome-rails'
gem 'gravatar_image_tag'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
